---
title: "Notes of linear algebra"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Preface

This is my learning notes of linear algebra


## Chapter 5

### Transpose and permutation
1. $(AA^{-1})^{T}=((A)^{-1})^{T}((A)^{T})$ You can construct a 3 by 3 matrix and you would get the idea of this formula
2. A matrix can be split to $A=LU$, where L represents lower triangle matrix, U represents upper traingle matrix, or $A=LDU$, where D represents diagnal matrix which only on the pivot there are elements
3. The cost of elimination of getting a lower traingle matrix is about $\frac{1}{3}n^{3}$, suppose it is a n by n matrix, and at the begining you want eliminate elements in the first column, probably it would take 99 * 100 times of calculation, assume it is $100^{2}$ times of calculation, the following calculation would cost $99^{2}$, and so on, after the intergration, the answer appears.
4. For permutaed identity matrix, $P^{T}=P^{-1}$

### Test git
